all:
  children:

    webservers:
      hosts:
        172.31.0.194:
          ansible_user: ec2-user
        172.31.0.171:
          ansible_user: ec2-user

    lb:
      hosts:
        172.31.6.8:
          ansible_user: ec2-user

    db:
      hosts:
        172.31.35.101:
          ansible_user: ec2-user