pipeline {
    agent any

    parameters {
        string(
            name: 'inventory',
            defaultValue: 'dev',
            description: 'This is the inventory file for the environment to deploy configuration'
        )

        string(
            name: 'ansible_tags',
            defaultValue: 'webserver',
            description: 'Ansible tags to run specific roles or tasks'
        )
    }

    stages {
        stage('Configure Ansible') {
            steps {
                sh '''
                    sed -i "s|roles_path = .*|roles_path = ${WORKSPACE}/roles|" ${WORKSPACE}/deploy/.ansible.cfg
                '''
            }
        }

        stage('Deploy') {
            steps {
                withCredentials([
                    sshUserPrivateKey(
                        credentialsId: 'ansible-sit-key',
                        keyFileVariable: 'SSH_KEY',
                        usernameVariable: 'SSH_USER'
                    )
                ]) {
                    sh '''
                        export ANSIBLE_CONFIG=${WORKSPACE}/deploy/.ansible.cfg

                        ansible-playbook \
                          -i inventory/${inventory}.yml \
                          playbooks/site.yml \
                          --tags "${ansible_tags}" \
                          -e env=${inventory} \
                          -e ansible_user=${SSH_USER} \
                          -e ansible_ssh_private_key_file=${SSH_KEY}
                    '''
                }
            }
        }
    }
}

