pipeline {
    agent any

    parameters {
        string(
            name: 'inventory',
            defaultValue: 'dev',
            description: 'This is the inventory file for the environment to deploy configuration'
        )
    }

    stages {
        stage('Configure Ansible') {
            steps {
                sh '''
                    sed -i "s|roles_path = .*|roles_path = ${WORKSPACE}/roles|" ${WORKSPACE}/deploy/.ansible.cfg
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    export ANSIBLE_CONFIG=${WORKSPACE}/deploy/.ansible.cfg
                    ansible-playbook -i inventory/${inventory}.yml playbooks/site.yml -e env=${inventory}
                '''
            }
        }
    }
}